import Head from "next/head";
import Image from "next/image";
// import styles from "../styles/global.css";

export default function Home() {
  return (
    <div className="bg-slate-600 p-4 pt-2">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="font-bold">Hey</main>
    </div>
  );
}
