import Head from "next/head";
import { ethers } from "ethers";
import { useState } from "react";
import Greeter from "../artifacts/contracts/Greeter.sol/Greeter.json";

const greeterAddress = "0x5FbDB2315678afecb367f032d93F642f64180aa3";

export default function Home() {
  const [greeting, setGreetingValue] = useState("");

  async function requestAccount() {
    await window.ethereum.request({ method: "eth_requestAccounts" });
  }

  async function fetchGreeting() {
    if (typeof window.ethereum !== "undefined") {
      const provider = new ethers.providers.Web3Provider(window.ethereum);
      const contract = new ethers.Contract(
        greeterAddress,
        Greeter.abi,
        provider
      );
      try {
        const data = await contract.greet();
        console.log("Data: ", data);
      } catch (err) {
        console.log("Error: ", err);
      }
    }
  }

  async function setGreeting() {
    if (!greeting) return;
    if (typeof window.ethereum !== "undefined") {
      await requestAccount();
      const provider = new ethers.providers.Web3Provider(window.ethereum);
      const signer = provider.getSigner();
      const contract = new ethers.Contract(greeterAddress, Greeter.abi, signer);
      const transaction = await contract.setGreeting(greeting);
      setGreetingValue("");
      await transaction.wait();
      fetchGreeting();
    }
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" font-bold">
        <button
          className="m-4 rounded-md bg-blue-900 p-2 px-4 font-extrabold text-white hover:scale-110 hover:rounded-xl hover:bg-gray-400 hover:text-blue-900"
          onClick={fetchGreeting}
        >
          Fetch Greeting
        </button>
        <button
          className="m-4 rounded-md bg-blue-900 p-2 px-4 font-extrabold text-white hover:scale-110 hover:rounded-xl hover:bg-gray-400 hover:text-blue-900"
          onClick={setGreeting}
        >
          Set Greeting
        </button>
        <div>
          <input
            className=" m-4 rounded-md bg-gray-300 py-1 px-3 placeholder-gray-700 hover:ml-6 hover:scale-110 hover:rounded-xl hover:bg-gray-400"
            onChange={(e) => setGreetingValue(e.target.value)}
            placeholder="Set Greeting..."
          />
        </div>
      </main>
    </div>
  );
}
